### ISSUE TITLE
Is this plugin finished? Can't seem to configure it correctly.

### ISSUE THREAD

**Issue by jordanurbs** [cyberboy666/peertube-plugin-auth-discourse#2]
Struggling to find any documentation or community experience on what I find to be a potentially very helpful plug-in.

Maybe I'm configuring the endpoints wrong or the empty warning dialogues on the peertube login page are placeholders?

Thanks for any input.

**Comment by cyberboy666** [comment]
hi @jordanurbs - it is working. thanks for the reminder, i need to document this plugin. (note that the version 0.0.8 from npm is not pushed to this github repo yet - here the latest is 0.0.7 which is not the current state)

to see it in action you can browse to https://videos.scanlines.xyz

in the peertube admin panel it looks like this:

![image](https://user-images.githubusercontent.com/12017938/100846160-76e25480-347e-11eb-8af2-0de23b05f1bc.png)

in the discourse admin settings it looks like this:

![image](https://user-images.githubusercontent.com/12017938/100846308-a6915c80-347e-11eb-8f83-10bd124a69cc.png)


maybe there is something else im forgetting right now. please let me know how you get on - i will update the readme with this/the info soon :)

**Comment by jordanurbs** [comment]
@langolierz thank you! This is just what I needed. I had the SSO Url and SSO secret fields filled out as as well as the SSO provider secrets and I think that was the issue.

All up and running now :)

**Comment by jordanurbs** [comment]
I seem to be experiencing this error when making a new user. When Discourse redirects to PeerTube, it gives this blank error dialogue. The new user has been activated in Discourse, but still does not exist within PeerTube.

This screenshot is after new user follows email confirmation link and clicks the 'click here to activate your email' button.

![Screen Shot 2020-12-03 at 12 59 41 PM](https://user-images.githubusercontent.com/44348964/101054210-6b1e8d00-3567-11eb-9ec7-718396b451a6.png)

In the PeerTube logs, this is the error:
```

warn[12/3/2020, 1:54:44 PM] Login error.

{
  "err": {
    "statusCode": 400,
    "status": 400,
    "code": 400,
    "message": "Cannot create such user: an actor with that name already exists.",
    "name": "access_denied",
    "stack": "access_denied: Cannot create such user: an actor with that name already exists.\n    at new AccessDeniedError (/app/code/server/node_modules/oauth2-server/lib/errors/access-denied-error.js:25:14)\n    at Object.<anonymous> (/app/code/server/dist/server/lib/oauth-model.js:97:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/code/server/node_modules/tslib/tslib.js:111:62)"
  }
}
```

**Comment by jordanurbs** [comment]
Update, I think I found the problem... apparently when you delete a user in Discourse, it doesn't delete the 'actor' in PeerTube. I am not sure if that refers to email, name, or username exactly. But I tried a new user with a new email domain, name, etc, and it worked fine.

**Comment by cyberboy666** [comment]
Ah yea I found this problem too. It is not easy to delete users in
peertube. This is related to the way activity pub works and the fact it
could lead to accounts being impersonated / taken over. If you really want
to do it still I wrote down how I managed it, here
https://github.com/langolierz/scanlines-technical-details/blob/master/experimenting-with-video-hosting.md#reusing-a-username
