### ISSUE TITLE
Still under development used in production somewhere?

### ISSUE THREAD

**Issue by dubwoc** [cyberboy666/peertube-plugin-auth-discourse#3]
I am interested in using this plugin but it is unclear if this is being maintained in some form or another.

Thank you!

**Comment by cyberboy666** [comment]
hello ! 

the plugin is still in use on https://videos.scanlines.xyz - you can go here to try it

it still works but not as seamlessly as it did before - before the login button was replaced with JOIN button that did this from the side panel - this broke in a peertube update but it still works if you go to the sign in page and then click the `sign in with discourse`

![image](https://user-images.githubusercontent.com/12017938/209051796-c86f5bdd-0c23-4e11-a1a5-a31cdf56de46.png)

i plan on updating this very soon, was just waiting for peertube v6 to come out as i thought it might break again... but this is out now so hopfully i will find some time to update it in coming months :)

**Comment by dubwoc** [comment]
Awesome thank you so much! I'll be sure to look out for updates. Happy New Year!

**Comment by cyberboy666** [comment]
@dubwoc just a heads up i pushed a new version of this plugin out today, fixing the issue with _hide default signup_

now when you are not logged in you will see JOIN button (instead on LOGIN/SIGN UP) which redirects to discourse auth directly:

![image](https://user-images.githubusercontent.com/12017938/211771700-bfa52f82-f070-43f5-a202-a4b73fa38dac.png)

**Comment by dubwoc** [comment]
Awesome, I will take on the task of updating peertube to v5 and give it a go! Thank you!
